"""add unique constraint on clubs(name)

Revision ID: 7d06a2c8856b
Revises: 9866186b8f94
Create Date: 2026-03-07 16:58:32.103580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d06a2c8856b'
down_revision: Union[str, None] = '9866186b8f94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_club_name', 'clubs', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_club_name', 'clubs', type_='unique')
    # ### end Alembic commands ###
