"""add unique constraint on clubs if needed

Revision ID: 80e9218c2e8c
Revises: 7d06a2c8856b
Create Date: 2026-03-07 17:08:14.978061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80e9218c2e8c'
down_revision: Union[str, None] = '7d06a2c8856b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
