"""add unique constraint on leagues(name, season)

Revision ID: 9866186b8f94
Revises: 28b57ca365b1
Create Date: 2026-03-07 16:45:41.101493

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9866186b8f94'
down_revision: Union[str, None] = '28b57ca365b1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_league_name_season', 'leagues', ['name', 'season'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_league_name_season', 'leagues', type_='unique')
    # ### end Alembic commands ###
