"""add api_football_id to clubs

Revision ID: d267a5efed06
Revises: 80e9218c2e8c
Create Date: 2026-03-07 18:09:44.815985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd267a5efed06'
down_revision: Union[str, None] = '80e9218c2e8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clubs', sa.Column('api_football_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clubs', 'api_football_id')
    # ### end Alembic commands ###
